org: andagaev
app: portfolio

service: Portfolio-tracker

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
    requirePoetryLockFile: true

provider:
  name: aws
  runtime: python3.12
  region: us-west-1
  architecture: arm64
  logRetentionInDays: 1
  versionFunctions: false
  environment:
    API_KEY: ${ssm:TELEGRAM_BOT_API_KEY}
    TG_CHAT_ID_2: ${ssm:TELEGRAM_BOT_CHAT_ID}

functions:
  rateHandler:
    handler: src.handler.get_stocks
    events:
      - schedule: cron(0 21 ? 11-02 MON-FRI *)
      - schedule: cron(0 20 ? 03-10 MON-FRI *)

package:
  exclude:
    - node_modules/**
    - .venv/**
