org: andagaev
app: portfolio

service: Portfolio-tracker

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    zip: true
    usePoetry: true
    requirePoetryLockFile: true
    pipCmdExtraArgs:
        - "--platform manylinux2014_aarch64"
        - "--implementation cp"
        - "--python-version 3.12"
        - "--only-binary=:all:"
        - "--upgrade"

provider:
  name: aws
  runtime: python3.12
  region: us-west-1
  architecture: arm64
  logRetentionInDays: 1
  versionFunctions: false

functions:
  rateHandler:
    handler: src.handler.get_stocks
    events:
      - schedule: rate(1 minute)

package:
  exclude:
    - node_modules/**
    - env/**